function obj = LabelEvents(obj)

D = obj.iEEGBandPass80;
Channeldir = D.chanlabels';

obj.CandidateHFOsFinalEventsLabels = cell(length(D.chanlabels),1);
NoiseLabel  = 'Artifacts';
SLabel      = 'Spike';
RLabel      = 'Ripple';
FRLabel     = 'FastRipple';
OtherLabel  = 'Others';

for i = 1:length(Channeldir)
    
    if isempty(obj.CandidateHFOsFinalEventsTimeStamps{i})
        continue
    elseif ~isempty(obj.CandidateHFOsFinalEventsTimeStamps{i})
        for j = 1:size(obj.CandidateHFOsFinalEventsTimeStamps{i},1)
            if obj.CandidateHFOsHFOsLabelsNoise{i}(j) % Noise
                obj.CandidateHFOsFinalEventsLabels{i}{j} = NoiseLabel;
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsFastRipple{i}(j)  % Spike
                obj.CandidateHFOsFinalEventsLabels{i}{j} = SLabel;
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsFastRipple{i}(j)  % Ripple
                obj.CandidateHFOsFinalEventsLabels{i}{j} = RLabel;
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsFastRipple{i}(j)  % FastRipple
                obj.CandidateHFOsFinalEventsLabels{i}{j} = FRLabel;
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsFastRipple{i}(j) % Spike + Ripple
                obj.CandidateHFOsFinalEventsLabels{i}{j} = [SLabel '_' RLabel];
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsFastRipple{i}(j) % Spike + FastRipple
                obj.CandidateHFOsFinalEventsLabels{i}{j} = [SLabel '_' FRLabel];
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsFastRipple{i}(j)  % Ripple + FastRipple
                obj.CandidateHFOsFinalEventsLabels{i}{j} = [RLabel '_' FRLabel];
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    obj.CandidateHFOsHFOsLabelsFastRipple{i}(j) % Spike + Ripple + FastRipple
                obj.CandidateHFOsFinalEventsLabels{i}{j} = [SLabel '_' RLabel '_' FRLabel];
            elseif ~obj.CandidateHFOsHFOsLabelsNoise{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsSpike{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsRipple{i}(j) && ...
                    ~obj.CandidateHFOsHFOsLabelsFastRipple{i}(j) % Others
                obj.CandidateHFOsFinalEventsLabels{i}{j} = OtherLabel;
            end
        end
        obj.CandidateHFOsFinalEventsLabels{i} = obj.CandidateHFOsFinalEventsLabels{i}';
    end
    
    
end
end


