function obj = SpatialNorm(obj)

resample = {obj.AnatFile;...
    'S4_BipolarElectrodesMask.nii';...
    'S4_CandidateHFOs.nii';...
    'S4_QualityHFOs.nii';...
    'S4_QualityFRHFOs.nii'};

SpatialNorm(obj.AnatFile,resample,obj.MainPath)

end

